site_name: MIIMOO STAND S1 Manuals
copyright: © 2024 MIIMOO | [プライバシーポリシー]
site_url: https://s1.miimoo.io
generator: false
use_directory_urls: false
markdown_extensions:
  - attr_list
  - md_in_html
theme:
  name: material
  language: zh
  logo: false
  features:
    - navigation.top
  palette:
    scheme: default
    primary: "#52b7bd"
    accent: "#52B7BD"
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - with-pdf:
      author: Your Name
      copyright: Your Copyright
      cover: true
      cover_title: Your Document Title
      cover_subtitle: Document Subtitle
      toc_level: 3
      output_path: pdf/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
